---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: linux
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    env:
      puppet_version: "${puppet_version:-5}"
provisioner:
  name: ansible
verifier:
  name: ansible
